---
# disable_proxmox_updates_of_files_in_lxc_containers/tasks/main.yml

- name: 'Create files to disable Proxmox from touch/modifying /etc/hosts inside LXC containers'
  ansible.builtin.copy:
    dest: '/etc/.pve-ignore.hosts'
    content: |
      # Ansible_managed
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Create files to disable Proxmox from touch/modifying /etc/hostname inside LXC containers'
  ansible.builtin.copy:
    dest: '/etc/.pve-ignore.hostname'
    content: |
      # Ansible_managed
    owner: 'root'
    group: 'root'
    mode: '0644'
